name: Lint

on: [push, pull_request]

jobs:
  Lint:
    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch. Without this if check, checks are duplicated since
    # internal PRs match both the push and pull_request events.
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Assert PR target is main
        if: github.event_name == 'pull_request' && github.repository == 'psf/black'
        run: |
          if [ "$GITHUB_BASE_REF" != "main" ]; then
              echo "::error::PR targeting '$GITHUB_BASE_REF', please refile targeting 'main'." && exit 1
          fi

      - name: Set up latest Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        uses: abatilo/actions-poetry@v2
        with:
            poetry-version: 1.2.0

      - name: Install dependencies
        run: poetry install --all-extras

      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.0
